---
- name: Install ruby
  hosts: rails_servers
  environment:
    RBENV_VERSION: "{{ ruby_version }}"

  pre_tasks:
    - name: rbenv と ruby-build プラグインがインストールされていることを確認する
      block:
        - name: rbenv がインストールされていることを確認する
          ansible.builtin.command: rbenv root
          changed_when: false
          register: rbenv_root_command
        - name: ruby-build プラグインがインストールされていることを確認する
          ansible.builtin.assert:
            that: ( rbenv_root_command.stdout + "/plugins/ruby-build" ) is exists

    - name: ruby-build plugin リポジトリを最新化する # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: "{{ rbenv_root_command.stdout }}/plugins/ruby-build"
        clone: false

  tasks:
    - name: Ruby をインストール
      ansible.builtin.command: rbenv install --skip-existing {{ ruby_version }}
      register: rbenv_install_command
      changed_when: rbenv_install_command.stdout != ""

    - name: Bundler をインストール (default gems に bundler が含まれない Ruby バージョンの場合)
      block:
        - name: Bundler がインストール済みかどうか確認する
          ansible.builtin.command: gem list bundler
          changed_when: false
          register: gem_list_bundler_command
        - name: Bundler をインストール
          when:
            - ruby_version is version_compare('2.6.0', '<')
            - gem_list_bundler_command.stdout in 'bundler'
          ansible.builtin.command: gem install bundler -v '< 2'
          changed_when: true

  post_tasks:
    - name: Ruby と Bundler のバージョンを確認する
      block:
        - name: Ruby と Bundler のバージョンを取得する
          ansible.builtin.command: "{{ item }}"
          loop:
            - ruby --version
            - bundle --version
          changed_when: false
          register: versions
        - name: Ruby と Bundler のバージョンを確認する
          ansible.builtin.debug:
            msg: "{{ versions.results | map(attribute='stdout') }}"
